// Copyright 2023 Samuel Kopp. All rights reserved. Apache-2.0 license.
export { addSignInMethod } from './add_sign_in_method.ts'
export type { OAuthClient } from './client.ts'
export { GitHub, Google } from './client.ts'
export { getSessionData } from './get_session_data.ts'
export { getSessionId } from './get_session_id.ts'
export { getSessionToken } from './get_session_token.ts'
export { handleCallback } from './handle_callback.ts'
export { isSignedIn } from './is_signed_in.ts'
export { signIn } from './sign_in.ts'
export { signOut } from './sign_out.ts'
export { native, OAuthStore, upstash } from './store.ts'
